Add aws-native and google-native automated sdk generation

diff --git a/native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml b/native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
--- a/native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
+++ b/native-provider-ci/providers/aws-native/repo/.github/workflows/nightly-sdk-generation.yml
@@ -5,7 +5,7 @@ on:
   workflow_dispatch: {}
 env:
   GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
-  PROVIDER: azure-native
+  PROVIDER: aws-native
   PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
   PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
@@ -15,13 +15,7 @@ env:
   TRAVIS_OS_NAME: linux
   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
-  ARM_CLIENT_ID: 30e520fa-12b4-4e21-b473-9426c5ac2e1e
-  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
-  ARM_ENVIRONMENT: public
-  ARM_LOCATION: westus2
-  ARM_SUBSCRIPTION_ID: 0282681f-7a9e-424b-80b2-96babd57a8a1
-  ARM_TENANT_ID: 706143bc-e1d4-4593-aee2-c9dc60ab9be7
-  GO111MODULE: on
+  AWS_REGION: us-west-2
   PULUMI_API: https://api.pulumi-staging.io
 jobs:
   generate-sdk:
@@ -32,6 +26,8 @@ jobs:
       uses: actions/checkout@v2
       with:
         lfs: true
+    - name: Unshallow clone for tags
+      run: git fetch --prune --unshallow --tags
     - name: Install Go
       uses: actions/setup-go@v2
       with:
@@ -42,9 +38,6 @@ jobs:
         repo: pulumi/pulumictl
     - name: Install Pulumi CLI
       uses: pulumi/action-install-pulumi-cli@v2
-    - uses: azure/login@v1
-      with:
-        creds: ${{ secrets.AZURE_RBAC_SERVICE_PRINCIPAL }}
     - name: Cleanup SDK Folder
       run: make clean
     - name: Preparing Git Branch
@@ -58,8 +51,8 @@ jobs:
       run: |-
         git add . 
         git commit -m "Preparing the SDK folder for regeneration"
-    - name: Update Submodules
-      run: make update_submodules
+    - name: Discovery
+      run: make discovery
     - name: Build codegen binaries
       run: make codegen
     - name: Build Schema + SDKs
@@ -67,16 +60,16 @@ jobs:
     - name: Git submodule commit hash
       id: vars
       run: echo ::set-output name=commit-hash::$(git rev-parse HEAD)
-      working-directory: azure-rest-api-specs
+      working-directory: aws-cloudformation-user-guide
     - name: Commit changes
       run: >-
         git add sdk
 
-        git commit -m "Regenerating SDKs based on azure-rest-api-specs @ ${{ steps.vars.outputs.commit-hash }}" || echo "ignore commit failure, may be empty"
+        git commit -m "Regenerating SDKs based on aws-cloudformation-user-guide @ ${{ steps.vars.outputs.commit-hash }}" || echo "ignore commit failure, may be empty"
 
         git add .
 
-        git commit -m "Regenerating based on azure-rest-api-specs @ ${{ steps.vars.outputs.commit-hash }}"
+        git commit -m "Regenerating based on aws-cloudformation-user-guide @ ${{ steps.vars.outputs.commit-hash }}"
 
         git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
     - name: Create PR
@@ -86,7 +79,7 @@ jobs:
         destination_branch: master
         github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
         pr_body: "*Automated PR*"
-        pr_title: Automated SDK generation @ azure-rest-api-specs ${{
+        pr_title: Automated SDK generation @ aws-cloudformation-user-guide ${{
           steps.vars.outputs.commit-hash }}
         author_name: pulumi-bot
         source_branch: generate-sdk/${{ github.run_id }}-${{ github.run_number }}
