more fixes

diff --git a/provider-ci/test-providers/aws/.github/workflows/publish.yml b/provider-ci/test-providers/aws/.github/workflows/publish.yml
--- a/provider-ci/test-providers/aws/.github/workflows/publish.yml
+++ b/provider-ci/test-providers/aws/.github/workflows/publish.yml
@@ -39,15 +39,15 @@ jobs:
       run: echo "Can't publish a prerelease version as a stable release. This is likely a bug in the calling workflow." && exit 1
     - name: Validate skipGoSdk
       if: inputs.skipGoSdk && inputs.isPrerelease == false
-      run: echo "Can't skip Go SDK for stable releases. This is likely a bug in the calling workflow." && exit 1    
-    - id: esc-secrets
-      name: Map environment to ESC outputs
-      uses: ./.github/actions/esc-action
+      run: echo "Can't skip Go SDK for stable releases. This is likely a bug in the calling workflow." && exit 1
     - name: Checkout Repo
       uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       with:
         submodules: true
-        persist-credentials: false
+        persist-credentials: false    
+    - id: esc-secrets
+      name: Map environment to ESC outputs
+      uses: ./.github/actions/esc-action
     - name: Setup tools
       uses: ./.github/actions/setup-tools
       with:
@@ -194,7 +194,11 @@ jobs:
     # Only run for non-prerelease, if the publish_go_sdk job was successful or skipped
     if: inputs.isPrerelease == false
     runs-on: ubuntu-latest
-    steps:      
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+        with:
+          persist-credentials: false      
       - id: esc-secrets
         name: Map environment to ESC outputs
         uses: ./.github/actions/esc-action
@@ -218,14 +222,14 @@ jobs:
     needs: create_docs_build
     
     runs-on: ubuntu-latest
-    steps:    
-    - id: esc-secrets
-      name: Map environment to ESC outputs
-      uses: ./.github/actions/esc-action
+    steps:
     - name: Checkout Repo
       uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       with:
-        persist-credentials: false
+        persist-credentials: false    
+    - id: esc-secrets
+      name: Map environment to ESC outputs
+      uses: ./.github/actions/esc-action
     - name: Clean up release labels
       uses: pulumi/action-release-by-pr-label@main
       with:
