Fix via TypeScript

diff --git a/native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml b/native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml
--- a/native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml
+++ b/native-provider-ci/providers/azure-native/repo/.github/workflows/nightly-sdk-generation.yml
@@ -89,7 +89,7 @@ jobs:
       run: echo commit-hash=$(git rev-parse HEAD) >> "$GITHUB_OUTPUT"
       working-directory: azure-rest-api-specs
     - name: Commit changes
-      run: >-
+      run: >
         git add sdk
 
         git commit -m "Regenerating SDKs based on azure-rest-api-specs @ ${{ steps.vars.outputs.commit-hash }}" || echo "ignore commit failure, may be empty"
@@ -98,7 +98,7 @@ jobs:
 
         git commit -m "Regenerating based on azure-rest-api-specs @ ${{ steps.vars.outputs.commit-hash }}"
 
-        git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
+        git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }} || echo "ignore commit failure, may be empty"
     - name: Create PR
       id: create-pr
       uses: repo-sync/pull-request@v2.6.2
