Add pull request/comment on PR workflow

diff --git a/.github/workflows/rollout-single-native-provider-workflow.yml b/.github/workflows/rollout-single-native-provider-workflow.yml
--- a/.github/workflows/rollout-single-native-provider-workflow.yml
+++ b/.github/workflows/rollout-single-native-provider-workflow.yml
@@ -25,8 +25,10 @@ jobs:
         with:
           repository: pulumi/pulumi-${{ github.event.inputs.provider_name }}
           path: pulumi-${{ github.event.inputs.provider_name }}
-      # - name: Delete existing workflows
-      #   run: rm pulumi-${{ github.event.inputs.provider_name }}/.github/workflows/*.yml
+      - name: Delete existing workflows
+        run: |
+          rm pulumi-${{ github.event.inputs.provider_name }}/.github/workflows/cleanup-artifacts.yml || echo "not found"
+          rm pulumi-${{ github.event.inputs.provider_name }}/.github/workflows/pull_request.yml || echo "not found"
       - name: Copy files from ci-mgmt to pulumi-${{ github.event.inputs.provider_name }}
         run: |
           cp -r ci-mgmt/native-provider-ci/providers/${{ github.event.inputs.provider_name }}/repo/. pulumi-${{ github.event.inputs.provider_name }}/.
