remove master.yml

diff --git a/.github/workflows/rollout-single-native-provider-workflow.yml b/.github/workflows/rollout-single-native-provider-workflow.yml
--- a/.github/workflows/rollout-single-native-provider-workflow.yml
+++ b/.github/workflows/rollout-single-native-provider-workflow.yml
@@ -29,6 +29,7 @@ jobs:
         run: |
           rm pulumi-${{ github.event.inputs.provider_name }}/.github/workflows/cleanup-artifacts.yml || echo "not found"
           rm pulumi-${{ github.event.inputs.provider_name }}/.github/workflows/pull_request.yml || echo "not found"
+          rm pulumi-${{ github.event.inputs.provider_name }}/.github/workflows/master.yml || echo "not found"
       - name: Copy files from ci-mgmt to pulumi-${{ github.event.inputs.provider_name }}
         run: |
           cp -r ci-mgmt/native-provider-ci/providers/${{ github.event.inputs.provider_name }}/repo/. pulumi-${{ github.event.inputs.provider_name }}/.
@@ -45,13 +46,11 @@ jobs:
           title: "Update GitHub Actions workflows."
           path: pulumi-${{ github.event.inputs.provider_name }}
           token: ${{ secrets.PULUMI_BOT_TOKEN }}
-      - name: test
-        run: echo ${{ github.repository }}
-      - name: Set PR to auto-merge
-        if: steps.create-pr.outputs.pull-request-operation == 'created'
-        uses: peter-evans/enable-pull-request-automerge@v1
-        with:
-          token: ${{ secrets.PULUMI_BOT_TOKEN }}
-          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
-          repository: pulumi/pulumi-${{ github.event.inputs.provider_name }}
-          merge-method: squash
+      # - name: Set PR to auto-merge
+      #   if: steps.create-pr.outputs.pull-request-operation == 'created'
+      #   uses: peter-evans/enable-pull-request-automerge@v1
+      #   with:
+      #     token: ${{ secrets.PULUMI_BOT_TOKEN }}
+      #     pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
+      #     repository: pulumi/pulumi-${{ github.event.inputs.provider_name }}
+      #     merge-method: squash
